### ISSUE TITLE
--version-file option

### ISSUE THREAD

**Issue by andreabz** [sayyid5416/pyinstaller#28]
Currently, --version-file is not listed in the pyinstaller options supported by this GitHub Action. Is this going to change?

**Comment by sayyid5416** [comment]
@andreabz I'll need more info. Can you elaborate more about what you want!

**Comment by andreabz** [comment]
Sorry for being not clear, I'll try again!
I'd like if your GitHub actions would support the pyinstaller --version-file option described [here](https://pyinstaller.org/en/stable/usage.html#windows-specific-options).

This option automatically includes the information provided in a predefined file, usually - or at least in my case - obtained by using [pyinstaller-versionfile](https://pypi.org/project/pyinstaller-versionfile/) on a yml file, and makes them visible in the Windows property pane of the app.

I find this option useful to know in advance the name, description and version of the application I'm going to run, or to easily provide context for bugs reported by other users.

Thanks.

**Comment by sayyid5416** [comment]
@andreabz Test with `version-file` branch, and report back if it's working or not.
```yaml
uses: sayyid5416/pyinstaller@version-file
```

**Comment by andreabz** [comment]
> @andreabz Test with `version-file` branch, and report back if it's working or not.
> 
> ```
> uses: sayyid5416/pyinstaller@version-file
> ```

Thanks. However, running this Action

`
name: Python Pyinstaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pyinstaller-build:
    runs-on: [ windows-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@version-file
        with:
          python_ver: '3.6'
          pyinstaller_ver: '==5.13.2'
          spec: 'myapp.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'myapp'
          options: --onefile, --name "myapp", --windowed, --version-file "file_version_info.txt"
`

 I got this error:

`
Run python "D:\a\_actions\sayyid5416\pyinstaller\version-file/src/checks.py"
Traceback (most recent call last):
  File "D:\a\_actions\sayyid5416\pyinstaller\version-file/src/checks.py", line 1, in <module>
    from actions import *
  File "D:\a\_actions\sayyid5416\pyinstaller\version-file\src\actions.py", line 2, in <module>
    from typing import Literal
ImportError: cannot import name 'Literal'
`

Shouldn't be dependencies installed and included in the Action itself?

**Comment by sayyid5416** [comment]
You are using python version 3.6, try to increase it

**Comment by sayyid5416** [comment]
@andreabz Have this worked for you?

**Comment by ZeroMarker** [comment]
I got same issue. Finally I find out why.
I edit workflow on github.com , save it.
Then I pull the code, add tag, push to trigger workflow.
I got this issue, the workflow seems always work on 3.6 python version.
The local workflow is wrong, so I delete it, clone & tag & push, it's work.

**Comment by sayyid5416** [comment]
@ZeroMarker so everything works fine now?

**Comment by ZeroMarker** [comment]
The final step is not work.
GitHub Action Output
```ps1
Warning: No files were found with the provided path: src\Notepad.spec. No artifacts will be uploaded.
Run echo "✔️ Executable **_(Notepad)_** uploaded successfully" >> $GITHUB_STEP_SUMMARY
```
My Action yaml
```yaml
name: Build and Release

on:
  push:
    tags:
      - 'v*'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: 3.9
          spec: 'src/notepad.py'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "Notepad", --windowed,
```
The artifact is generated, but not uploaded.
How to fix this?

**Comment by ZeroMarker** [comment]
I realized that I misunderstand the purpose of this action. It's not upload to releases, because release need auth of github.

**Comment by sayyid5416** [comment]
> I realized that I misunderstand the purpose of this action. It's not upload to releases, because release need auth of github.

@ZeroMarker  No. It uploads the artifact. I need to look at the issue.

**Comment by sayyid5416** [comment]
Do you have "notepad.py" in your src folder?

**Comment by sayyid5416** [comment]
Can you create a public repo, and try to reproduce the issue there?

**Comment by ZeroMarker** [comment]
My repo:
https://github.com/ZeroMarker/notepad
I can see the artifact below:
https://github.com/ZeroMarker/notepad/actions/runs/12063677677

**Comment by sayyid5416** [comment]
Action is working as expected. **Executable is being uploaded correctly** but spec file is not being detected _(which is just an additional feature)_. I'll take a look into it.
> You can safely ignore that warning in the meantime.

Thanks for reporting.

**Comment by sayyid5416** [comment]
@ZeroMarker Spec file issue solved in #30 . I'll release new version soon.

**Comment by sayyid5416** [comment]
@ZeroMarker Released. Now your action should work fine.

**Comment by numbworks** [comment]
I stumbled upon this thread while searching for a better way to pass Windows-executable-related metadata to PyInstaller in a CI/CD pipeline.

One of the main differences between `PyInstaller` and `Nuitka` is that the first one uses Version Info Files (not an easy way to provide metadata on-the-fly), while the second one uses simpler, high-level, command-line flags you can feed values to. In addition to that, `PyInstaller` doesn't allow you to verify the Version Info File before starting the building process.

To fill the gap, I wrote a Python library from scratch that fixes these two issues: `nwversioninfofiles`.

If you banged your head for days on this like me, feel free to give my library a try:

- `pip install --extra-index-url https://numbworks.github.io nwversioninfofiles==1.0.0`
- `pip install "https://github.com/numbworks/nwversioninfofiles/archive/refs/tags/v1.0.0.zip#subdirectory=src"`
- `pip install 'git+https://github.com/numbworks/nwversioninfofiles.git@v1.0.0#egg=nwversioninfofiles&subdirectory=src'`

**Source code here:**
https://github.com/numbworks/nwversioninfofiles

**Documentation and architectural diagram here:**
https://github.com/numbworks/nwversioninfofiles/blob/master/docs/docs-nwversioninfofiles.md

What `Nuitka` does:

```cmd
python.exe -m nuitka \
    --company-name="numbworks" \
    --copyright="numbworks" \
    --file-description="An app that does something." \
    --file-version="1.0.0" \
    --product-name="app" \
    --product-version="1.0.0" \
    --trademark="numbworks" \
    --windows-icon-from-ico="app.ico" \
    ... \
    app.py
```

What `PyInstaller` does:

```cmd
python.exe -m PyInstaller \
    --version-file="version_info_file.txt" \
    --icon="app.ico" \
    ... \
    app.py
```

What `nwversioninfofiles` does:

```cmd
python.exe -m nwversioninfofiles \
	--company_name "numbworks" \
	--legal_copyright "numbworks" \
	--file_description "An app that does something." \
	--file_version "1.0.0" \
	--product_name "numbworks" \
	--original_filename "app.exe" \
	--output_path "version_info_file.txt" \
	--verify
```
